// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohnzonlopkfsmyvynnhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9obnpvbmxvcGtmc215dnlubmhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NTM1MjUsImV4cCI6MjA2MjIyOTUyNX0.PlFxfkTgIkT_Czw6e_WhoyVtcd7sy6G8FXSu-JMrNx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);